name: continuous-delivery
on:
  push:
    branches: [main]
jobs:
  # CALL WORKFLOW tag-release
  tag-release:
    uses: indigo-tangerine/shared-workflows/.github/workflows/tag-release.yml@main

  # CALL WORKFLOW changelog
  update-changelog:
    needs: [tag-release]
    uses: indigo-tangerine/shared-workflows/.github/workflows/update-changelog.yml@main
    secrets:
      access_token: ${{ secrets.CICD_AUTOMATION_PAT }}
