name: continuous-integration-pr
on:
  pull_request:
    branches: ["main"]

jobs:
  # CALL WORKFLOW tfm-validate-plan code validation and lint
  validate-iac:
    uses: indigo-tangerine/shared-workflows/.github/workflows/tfm-validate.yml@main
    with:
      terraform-dir: "."

  # CALL WORKFLOW tfm-security tfsec scan
  security-scan:
    uses: indigo-tangerine/shared-workflows/.github/workflows/tfm-security.yml@main
    with:
      terraform-dir: "."

  # CALL WORKFLOW tfm-docs update terraform documentation
  tfm-docs:
    uses: indigo-tangerine/shared-workflows/.github/workflows/tfm-docs.yml@main
    needs: [validate-iac, security-scan]
    with:
      working-dir: "."
